accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path

from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path

from .views import (
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
)

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("tasks/", include("tasks.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

accounts/models.py
# from django.db import models

# Create your models here.

projects/models.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField("auth.User", related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.conf import settings
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project",
        related_name="tasks",
        on_delete=models.CASCADE,
    )

    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from projects.models import Project


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.members = self.request.user
        item.save()
        return reverse_lazy("create_project")


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)

tasks/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from tasks.models import Task


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.assignee = self.request.user
        item.save()
        return reverse_lazy("project_detail.html")


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/update.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/projects/create.html
<!doctype html>
<html>
    <head>
        <title>Tracker</title>
    </head>
    <body>
        {% block content %}
            <main>
                <div class="narrow-form">
                    <h1>Create a new project</h1>
                    <form method="post">
                        <input type="text" name="name">
                        <textarea name-"description">
                            <select name="members">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button>Create</button>
                            </form>
                        </div>
        {% endblock content %}
    </body>
</html>

projects/templates/projects/detail.html
{% load markdownify %}
{{'Some *test* [link](#)'|markdownify }}
<!doctype html>
<html>
    <head>
        <title>Tracker</title>
    </head>
    <body>
        {% block content %}
            <main>
                <div>
                    <h1>{{ project.name }}</h1>
                    <p>This project has no task</p>
                    {{ project.description|markdownify }}
                    <h2>Tasks</h2>
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Assignee</th>
                                <th>Start date</th>
                                <th>Due Date</th>
                                <th>is completed</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for tasks in project.item.all %}
                                <tr>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </main>
        {% endblock content %}
    </div>
</body>
</html>

projects/templates/projects/list.html
<!doctype>
<html>
    <head>
        <title>Tracker</title>
    </head>
    <body>
        {% block content %}
            <main>
                <div>
                    <h1>My Projects</h1>
                    <p>
                        <a href="{% url 'list_project_create' %}">Create a new project</a>
                    </p>
                    <p>You are not assigned to any projects</p>
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Number of tasks</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for project in project_list %}
                                <tr>
                                    <td>
                                    </td>
                                    <td>
                                        <a href="{% url 'show_project_detail' list.id %}">{{ project.name }}</a>
                                    </td>
                                    <td> {{ project.name }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
        {% endblock content %}
    </main>
</div>
</body>
</html>

tasks/templates/tasks/create.html
<!doctype html>
<html>
    <head>
        <title>Tracker</title>
    </head>
    <body>
        {% block content %}
            <main>
                <div class="narrow-form">
                    <h1>Create a new task</h1>
                    <form method="post">
                        <input type="text" name="name">
                        <input type="text" name="start_date">
                        <input type="text" name="due_date">
                        <select name="projects">
                            <select name ="assignee">
                                <select name="members">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <button>Create</button>
                                </form>
                            </div>
        {% endblock content %}
    </body>
</html>

tasks/templates/tasks/list.html
<!doctype>
<html>
    <head>
        <title>Tracker</title>
    </head>
    <body>
        {% block content %}
            <main>
                <div>
                    <h1>My Tasks</h1>
                    <p>You have no tasks</p>
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Start date</th>
                                <th>End date</th>
                                <th>Is completed</th>
                                <th>Number of tasks</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for task in tasks %}
                                <tr>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
        {% endblock content %}
    </main>
</div>
</body>
</html>